#!/usr/bin/env python3
"""Regenerate GLOSSARY.md — the A–Z English↔Polish index of every term page.

Walks the seven unit folders, reads each keyword page's H1 (``# English / Polski``),
and writes one alphabetical table. Run from the repo root:

    python3 tools/build_glossary.py

The glossary is generated — edit the term pages, not the table.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

UNITS = {
    "01_Chemistry_of_Life": "1",
    "02_Cells_as_Living_Systems": "2",
    "03_Cellular_Processes": "3",
    "04_DNA_and_Cell_Division": "4",
    "05_Genetics_and_Biotechnology": "5",
    "06_Evolution_and_Diversity_of_Life": "6",
    "07_Ecological_Principles": "7",
}

HEADER = """# Glossary A–Z / Słowniczek A–Z

Every term in the library, in one table — English on the left, Polish on the right, with the unit it belongs to. Click a term for its full page (two-column explanation + AP deep dive).

Wszystkie hasła biblioteki w jednej tabeli — angielski po lewej, polski po prawej, z numerem działu. Kliknij hasło, by przejść do pełnej strony.

*(Generated by `tools/build_glossary.py` — edit the term pages, not this table.)*

| English | Polski | Unit |
|---|---|---|
"""


def main() -> int:
    rows: list[tuple[str, str, str, str]] = []
    problems: list[str] = []
    for unit_dir, unit_no in UNITS.items():
        base = REPO / unit_dir
        if not base.is_dir():
            problems.append(f"missing unit folder: {unit_dir}")
            continue
        for page in sorted(base.glob("*/README.md")):
            first = page.read_text(encoding="utf-8").lstrip().splitlines()[0]
            m = re.match(r"#\s+(.+?)\s+/\s+(.+)", first)
            if not m:
                problems.append(f"{page.relative_to(REPO)}: H1 is not '# English / Polski' ({first!r})")
                continue
            en, pl = m.group(1).strip(), m.group(2).strip()
            rel = f"{unit_dir}/{page.parent.name}/README.md"
            rows.append((en, pl, rel, unit_no))
    if problems:
        for p in problems:
            print(f"PROBLEM: {p}", file=sys.stderr)
        return 1
    rows.sort(key=lambda r: r[0].casefold())
    out = HEADER + "".join(
        f"| [{en}]({rel}) | {pl} | {unit_no} |\n" for en, pl, rel, unit_no in rows
    )
    out += f"\n**{len(rows)} terms.**\n"
    (REPO / "GLOSSARY.md").write_text(out, encoding="utf-8")
    print(f"GLOSSARY.md written: {len(rows)} terms")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
